/* NEXUS AI Assistant - static provider abstraction */
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const MODES={Explain:'Explain clearly with a simple analogy and a concise example.',Teach:'Act as a patient tutor. Ask one question at a time and check understanding.', 'Quiz Me':'Quiz me interactively. Ask one question at a time and wait for my answer.',Summarize:'Summarize the material with key points, definitions, and a short recap.',Practice:'Give me a worked example, then a similar problem for me to try.',Brainstorm:'Help me generate and organize creative ideas without judging them.'};
const KEY='nexus-state-v1'; let state=JSON.parse(localStorage.getItem(KEY)||'null')||{chats:[],current:null,mode:'Explain',subject:'General',theme:'dark',apiKey:'',localReady:false}; let controller=null;
function persist(){localStorage.setItem(KEY,JSON.stringify(state))} function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)}
function current(){return state.chats.find(c=>c.id===state.current)}
function newChat(){const c={id:uid(),title:'New chat',messages:[],updated:Date.now()};state.chats.unshift(c);state.current=c.id;persist();render()}
function renderHistory(){const q=$('#chatSearch').value.toLowerCase();$('#history').innerHTML=state.chats.filter(c=>c.title.toLowerCase().includes(q)).map(c=>`<div class="chat-item ${c.id===state.current?'active':''}" data-id="${c.id}"><span>▱</span><span class="chat-name">${esc(c.title)}</span><button class="chat-menu" data-menu="${c.id}" aria-label="Chat options">•••</button></div>`).join('')||'<p class="privacy">No chats yet. Start a new one.</p>'}
function render(){if(!state.chats.length)newChat();renderHistory();const c=current();$('#messages').innerHTML=c.messages.map((m,i)=>messageHTML(m,i)).join('');$('#welcome').style.display=c.messages.length?'none':'block';$('#apiKey').value=state.apiKey||'';document.body.classList.toggle('light',state.theme==='light');$('#themeLabel').textContent=state.theme==='light'?'Dark mode':'Light mode';$('#themeIcon').textContent=state.theme==='light'?'☾':'☀';$('#providerPill').textContent=state.apiKey?'Gemini connected':state.localReady?'Local model ready':'Not connected';scrollBottom()}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function markdown(s){let out=esc(s).replace(/```(\w*)\n?([\s\S]*?)```/g,(_,l,c)=>`<pre><button class="copy-code" data-copy="${encodeURIComponent(c)}">Copy</button><code>${c}</code></pre>`);out=out.replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code class="inline-code">$1</code>').replace(/^[-*] (.*)$/gm,'<li>$1</li>').replace(/(<li>.*<\/li>\n?)+/g,'<ul>$&</ul>').replace(/\n\n/g,'</p><p>').replace(/\n/g,'<br>');return `<p>${out}</p>`}
function messageHTML(m,i){if(m.role==='user')return `<div class="message user"><div class="avatar">You</div><div class="bubble">${esc(m.content).replace(/\n/g,'<br>')}</div></div>`;return `<div class="message assistant"><div class="avatar">✦</div><div class="bubble">${markdown(m.content)}${!m.error?`<div class="reply-actions"><button data-action="copy" data-index="${i}">▣ Copy</button><button data-action="regen" data-index="${i}">↻ Regenerate</button><button data-action="note" data-index="${i}">＋ Save to Notes</button></div>`:''}</div></div>`}
function scrollBottom(){const v=$('#chatView');requestAnimationFrame(()=>v.scrollTop=v.scrollHeight)}
function renderModes(){ $('#modeRow').innerHTML=Object.keys(MODES).map(x=>`<button class="mode-chip ${state.mode===x?'active':''}" data-mode="${x}">${x}</button>`).join('')}
function setLoading(x){$('#sendBtn').style.display=x?'none':'block';$('#stopBtn').style.display=x?'block':'none'}
function apiError(e){let msg=e.message||'Something went wrong.';if(/429|quota|rate/i.test(msg))msg='Daily free limit reached, try again later or switch provider.';return msg}
async function send(text=$('#prompt').value.trim()){if(!text||controller)return;if(!state.apiKey&&!state.localReady){openSettings();toast('Connect Gemini or download a local model first.');return}const c=current();c.messages.push({role:'user',content:text});c.title=c.title==='New chat'?text.slice(0,38):c.title;c.updated=Date.now();$('#prompt').value='';resize();const ai={role:'assistant',content:''};c.messages.push(ai);persist();render();setLoading(true);controller=new AbortController();try{if(state.apiKey)await gemini(c,ai,controller.signal);else throw new Error('The on-device model is not available yet. Download it in Settings.')}catch(e){if(e.name!=='AbortError'){ai.error=true;ai.content=apiError(e);toast(ai.content)}}finally{controller=null;setLoading(false);persist();render()}}
async function gemini(c,ai,signal){const contents=c.messages.slice(0,-1).map(m=>({role:m.role==='assistant'?'model':'user',parts:[{text:m.content}]}));const system=`You are NEXUS, a helpful school study assistant. Mode: ${state.mode} — ${MODES[state.mode]} Subject: ${state.subject}. Be accurate, encouraging, and concise. Use Markdown. For math, use LaTeX delimiters.`;const url='https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:streamGenerateContent?alt=sse&key='+encodeURIComponent(state.apiKey);const r=await fetch(url,{method:'POST',signal,headers:{'Content-Type':'application/json'},body:JSON.stringify({system_instruction:{parts:[{text:system}]},contents,generationConfig:{temperature:.7}})});if(!r.ok){let j=await r.json().catch(()=>({}));throw new Error(j.error?.message||`Request failed (${r.status})`)}const reader=r.body.getReader(),decoder=new TextDecoder();let buf='';while(true){const {value,done}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});const lines=buf.split('\n');buf=lines.pop();for(const line of lines){if(!line.startsWith('data:'))continue;try{const j=JSON.parse(line.slice(5));const part=j.candidates?.[0]?.content?.parts?.[0]?.text;if(part){ai.content+=part;render();scrollBottom()}}catch{}}}}
function openSettings(){$('#settingsDialog').showModal()}function closeSettings(){if($('#settingsDialog').open)$('#settingsDialog').close();render()}
function resize(){const t=$('#prompt');t.style.height='auto';t.style.height=Math.min(t.scrollHeight,150)+'px'}
$('#newChat').onclick=newChat;$('#chatSearch').oninput=renderHistory;$('#prompt').oninput=resize;$('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};$('#sendBtn').onclick=()=>send();$('#stopBtn').onclick=()=>{controller?.abort();toast('Generation stopped.')};$('#settingsBtn').onclick=openSettings;$('#topSettings').onclick=openSettings;$('#closeSettings').onclick=closeSettings;$('#doneSettings').onclick=closeSettings;$('#saveKey').onclick=()=>{state.apiKey=$('#apiKey').value.trim();persist();toast(state.apiKey?'Gemini key saved.':'Key removed.');render()};$('#clearKey').onclick=()=>{$('#apiKey').value='';state.apiKey='';persist();render()};$('#toggleKey').onclick=()=>$('#apiKey').type=$('#apiKey').type==='password'?'text':'password';$('#themeBtn').onclick=()=>{state.theme=state.theme==='light'?'dark':'light';persist();render()};$('#openSidebar').onclick=()=>{$('#sidebar').classList.add('open');$('#scrim').classList.add('show')};$('#closeSidebar').onclick=$('#scrim').onclick=()=>{$('#sidebar').classList.remove('open');$('#scrim').classList.remove('show')};
$('#modeRow').onclick=e=>{if(e.target.dataset.mode){state.mode=e.target.dataset.mode;persist();renderModes()}};$('#subject').onchange=e=>{state.subject=e.target.value;persist()};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$('#geminiTab').classList.toggle('hidden',b.dataset.tab!=='gemini');$('#localTab').classList.toggle('hidden',b.dataset.tab!=='local')});$('#downloadModel').onclick=async()=>{if(!('gpu' in navigator)){toast('WebGPU is not available in this browser.');return}const bar=$('#progressBar');for(let i=0;i<=100;i+=5){await new Promise(r=>setTimeout(r,70));bar.style.width=i+'%'}state.localReady=true;persist();$('#localStatus').textContent='Model ready (demo downloader).';toast('Local model download complete.');render()};
$('#history').onclick=e=>{const item=e.target.closest('.chat-item');if(!item)return;if(e.target.dataset.menu){const c=state.chats.find(x=>x.id===e.target.dataset.menu);const action=prompt('Type rename or delete:', 'rename');if(action==='delete'){state.chats=state.chats.filter(x=>x!==c);if(state.current===c.id)state.current=state.chats[0]?.id||null}else if(action==='rename'){const n=prompt('Chat name:',c.title);if(n)c.title=n}persist();render()}else{state.current=item.dataset.id;persist();render()}};
$('#messages').onclick=e=>{const b=e.target.closest('button');if(!b)return;const c=current(),i=+b.dataset.index;if(b.dataset.copy){navigator.clipboard.writeText(decodeURIComponent(b.dataset.copy));toast('Code copied.');return}if(b.dataset.action==='copy'){navigator.clipboard.writeText(c.messages[i].content);toast('Reply copied.')}if(b.dataset.action==='note'){const notes=JSON.parse(localStorage.getItem('nexus-notes')||'[]');notes.push({text:c.messages[i].content,date:new Date().toISOString()});localStorage.setItem('nexus-notes',JSON.stringify(notes));toast('Saved to Notes.')}if(b.dataset.action==='regen'){c.messages.splice(i);persist();render();send(c.messages[c.messages.length-1]?.content||'')}};document.querySelectorAll('[data-suggestion]').forEach(b=>b.onclick=()=>{ $('#prompt').value=b.dataset.suggestion;resize();send()});renderModes();render();
